name: Build and deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Slaskit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: registry.knatofs.se
          username: mats
          password: ${{ secrets.DCR_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push api
        uses: docker/build-push-action@v4
        with:
          push: true
          cache-from: type=gha,scope=api
          cache-to: type=gha,scope=api,mode=max
          tags: registry.knatofs.se/type-test:${{github.sha}}
      - name: Deploy scripted application
        uses: matst80/slask-action@main
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        with:
          k8sConfig: ${{ secrets.K8S_CONFIG }}
          scriptPath: deploy.cjs
